apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-py
  namespace: application
  labels:
    app: app-py
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-py
  template:
    metadata:
      labels:
          app: app-py
    spec:
      containers:
        - name: app-py
          image: matiasolivar/desafio2-flask:v1.0
          ports:
          - containerPort: 5000
          volumeMounts:
            - name: app-py
              mountPath: /var/app-py
      volumes:
      - name: app-py
        persistentVolumeClaim:
            claimName: app-py
      



