apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-py
  namespace: application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Asegúrate de cambiar esto según tus necesidades
